# front/nginx.conf
server {
  listen 3002;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  # Fallback para SPA (history mode)
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Opcional: redirect healthcheck
  location /health {
    return 200 'ok';
    add_header Content-Type text/plain;
  }

  # Ajuste cabeçalhos se precisar CORS ou CSP aqui
  # add_header X-Frame-Options "DENY";
}
